### ISSUE TITLE
Is the chinese deck simplified or traditional?

### ISSUE THREAD

**Issue by dynuel** [dseevr/glossika-anki-decks#1]
Hi, could I please ask you, is the chinese deck here simpliefied or traditional? I am looking for the simplified one. Thank you very much.

**Comment by dseevr** [comment]
The generated files are traditional Chinese characters.  The input files only contained traditional Chinese, and the list of the most frequent Chinese characters is explicitly converted to traditional here:

https://github.com/dseevr/glossika-anki-decks/blob/9daa3026ad2527ef3def6638a1e15e99e863b196/lib/language_tree.rb#L14

You could use this `Tradsim` gem to convert all the characters in the text files to simplified.

https://github.com/erinata/tradsim
